! -*- bgp -*-
!
! BGPd sample configuratin file
!
! $Id: bgpd.conf.sample,v 1.1 2002/12/13 20:15:29 paul Exp $
!

hostname bgpd-S3
password en
enable password en

router bgp 3
  bgp router-id 9.0.1.2
  network 13.0.0.0/8
  network 13.0.1.0/24
  no bgp network import-check
  neighbor 9.0.1.1 remote-as 2
  neighbor 9.0.1.1 ebgp-multihop 2
  neighbor 9.0.1.1 timers 3 9
  
  ! Set lower local preference so rogue AS is preferred
  neighbor 9.0.1.1 route-map DEPREF in

route-map DEPREF permit 10
  set local-preference 100

log file /tmp/S3-bgpd.log

